installDir = "/Applications"
profilesDir = "~/ChromiumProfiles"
iconsDir = "./icons"

[[bundles]]
browser = "chrome"
key = "soracom-design-system-docs"
displayName = "Soracom Design System Docs"
workspace = "4_Soracom_Design_System_Docs"
id = "soracom-design-system-docs"
icon = "https://assets.soracom.io/icon/soracom/platform/sds.svg"
iconColor = "#FFFFFF"
iconBackgroundColor = "#34CDD7"

[[bundles]]
browser = "chromium"
key = "user-console-monorepo"
displayName = "User Console Monorepo"
workspace = "6_User_Console"
icon = "https://assets.soracom.io/icon/gadgets/laptop.svg"
iconColor = "#FFFFFF"
id = "user-console-monorepo"
iconBackgroundColor = "#7C5CFF"

[[bundles]]
browser = "chrome"
key = "slack"
displayName = "Slack"
icon = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Slack_icon_2019.svg/3840px-Slack_icon_2019.svg.png"
iconBackgroundColor = "#4A154B"
workspace = "12_Slack"
id = "slack"
iconInset = "medium"
defaultUrl = "https://soracom.slack.com"
appType = "app"

[[bundles]]
browser = "chrome"
key = "soracom-design-system"
displayName = "Soracom Design System"
icon = "https://assets.soracom.io/icon/soracom/platform/sds.svg"
iconColor = "#F59E0B"
iconBackgroundColor = "#3B82F6"
workspace = "4_Design_System"
id = "soracom-design-system"
iconInset = "medium"
